### ISSUE TITLE
searchview doesn't work

### ISSUE THREAD

**Issue by zabihy** [beraybentesen/material-searchview-xamarin-android#1]
The SearchView doesn't appear. I don't see any searchbar or Search Icon in the toolbar.
this is my Main.axml
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent">
  <FrameLayout
        android:id="@+id/toolbar_container"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:minHeight="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        android:paddingTop="0dp"/>
    <com.materialsearchview.MaterialSearchView
        android:id="@+id/search_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />
  </FrameLayout>
</LinearLayout>`

and the MainActivity.cs
`protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);

            // Set our view from the "main" layout resource
            SetContentView(Resource.Layout.Main);

            mToolbar = FindViewById<SupportToolbar>(Resource.Id.toolbar);

            SetSupportActionBar(mToolbar);
            if (Build.VERSION.SdkInt < BuildVersionCodes.Kitkat)
            {
                mToolbar.SetPadding(0, 0, 0, 0);
            }

            AccountHeader headerResult = 
                new AccountHeaderBuilder()
                    .WithActivity(this)
                    .WithHeaderBackground(Resource.Drawable.header)
                    .AddProfiles(
                        new ProfileDrawerItem().WithName("Mike Penz").WithEmail("mikepenz@gmail.com")
                    ).Build();

            Drawer result = new DrawerBuilder()
            .WithActivity(this)
            .WithAccountHeader(headerResult)
            .WithToolbar(mToolbar)
            .AddDrawerItems(new DividerDrawerItem()).Build();

            // create our manager instance after the content view is set
            SystemBarTintManager tintManager = new SystemBarTintManager(this);
            // enable status bar tint
            tintManager.StatusBarTintEnabled = true;
            // enable navigation bar tint
            tintManager.SetNavigationBarTintEnabled(true);

            // set the transparent color of the status bar, 20% darker
            tintManager.SetTintColor(Color.ParseColor("#20000000"));

            var materialSearchView = FindViewById<MaterialSearchView>(Resource.Id.search_view);

            materialSearchView.SetSuggestionIcon(ContextCompat.GetDrawable(this, Resource.Drawable.userTextIcon));
            materialSearchView.SetOnQueryTextListener(this);
            var searchAdapter = new SearchAdapter(this, new[] { "m", "m2" }, ContextCompat.GetDrawable(this, Resource.Drawable.login), true, this);
            materialSearchView.SetAdapter(searchAdapter);
            materialSearchView.IOnClickListener = this;
        }
    }`

**Comment by beraybentesen** [comment]
You must setup your own toolbar with items. 

Create menu folder in resources and add a new menu xml.

Then create menu in activity like this : 

public override bool OnCreateOptionsMenu(IMenu menu)
		{
			MenuInflater.Inflate(Resource.Menu.menu_search, menu);
			IMenuItem item = menu.FindItem(Resource.Id.action_search);
			materialSearchView.SetMenuItem(item);
			return true;
		}

That is all you need.

**Comment by zabihy** [comment]
Great!!! Works like a charm!! thanks very much!!
